AWSTemplateFormatVersion: 2010-09-09
Description: Create a resource on given ReST API

Parameters:
  RestApiId:
    Type: String
    Description: The ID of the REST API Gateway.
  ParentResourceId:
    Type: String
    Description: The ID of the root resource on the REST API Gateway.
  ResourceName:
    Type: String
    Description: The name of the resource.

Resources:
  LambdaResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApiId
      ParentId: !Ref ParentResourceId
      PathPart: !Ref ResourceName

Outputs:
  ResourceId:
    Value: !Ref LambdaResource
    Description: The ID of the created resource