AWSTemplateFormatVersion: 2010-09-09

Parameters:
  User:
    Type: String
    Description: The name of the user to create.
    Default: deployer

Resources:
  S3BucketPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Users:
        - !Ref User
      PolicyName: COSQS3BucketPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:PutObject
              - s3:GetObject
            Resource: arn:aws:s3:::*

  IAMPolicyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Users:
        - !Ref User
      PolicyName: IAMPolicyPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - iam:PassRole
            Resource: '*'

  EC2Policy:
    Type: AWS::IAM::Policy
    Properties:
      Users:
        - !Ref User
      PolicyName: EC2Policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ec2:DescribeSecurityGroups
              - ec2:DescribeSubnets
              - ec2:DescribeVpcs
            Resource: '*'

  CloudFormationPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Users:
        - !Ref User
      PolicyName: CloudFormationPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:*
            Resource: '*'

  CloudWatchLogPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Users:
        - !Ref User
      PolicyName: CloudWatchLogPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
            Resource: '*'

  LambdaFunctionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Users:
        - !Ref User
      PolicyName: LambdaFunctionPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - lambda:CreateFunction
              - lambda:DeleteFunction
              - lambda:GetFunction
              - lambda:ListFunctions
              - lambda:UpdateFunction
              - lambda:InvokeFunction
              - lambda:GetFunctionConfiguration
              - lambda:UpdateFunctionConfiguration
              - lambda:PublishVersion
              - lambda:GetFunctionVersion
              - lambda:ListFunctionVersions
              - lambda:UpdateFunctionVersion
              - lambda:DeleteFunctionVersion
              - lambda:GetFunctionCode
              - lambda:UpdateFunctionCode
              - lambda:GetPolicy
              - lambda:PutPolicy
              - lambda:DeletePolicy
              - lambda:AddPermission
              - lambda:RemovePermission
              - lambda:GetFunctionEventTriggers
              - lambda:PutFunctionEventTrigger
              - lambda:DeleteFunctionEventTrigger
              - lambda:TagResource
              - lambda:UntagResource
              - lambda:ListTagsForResource
            Resource: '*'

  APIGatewayPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Users:
        - !Ref User
      PolicyName: APIGatewayPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - apigateway:GET
              - apigateway:POST
              - apigateway:PUT
              - apigateway:DELETE
              - apigateway:CreateRestApi
              - apigateway:DeleteRestApi
              - apigateway:UpdateRestApi
              - apigateway:ImportRestApi
              - apigateway:ExportRestApi
              - apigateway:CreateResource
              - apigateway:DeleteResource
              - apigateway:UpdateResource
              - apigateway:CreateMethod
              - apigateway:DeleteMethod
              - apigateway:UpdateMethod
              - apigateway:CreateDeployment
              - apigateway:DeleteDeployment
              - apigateway:UpdateDeployment
              - apigateway:CreateStage
              - apigateway:DeleteStage
              - apigateway:UpdateStage
            Resource: '*'

