AWSTemplateFormatVersion: 2010-09-09

Parameters:
  S3Bucket:
    Type: String
    Description: The name of the S3 bucket containing the Lambda function code.
  S3Key:
    Type: String
    Description: The key of the S3 object containing the Lambda function code.
  FunctionName:
    Type: String
    Description: The name of the Lambda function to create.
  Runtime:
    Type: String
    Description: The runtime environment for the Lambda function.
  Handler:
    Type: String
    Description: The Lambda function handler.
  LambdaExecutionRoleArn:
    Type: String
    Description: The ARN of the Lambda execution role.

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunctionName
      Runtime: !Ref Runtime
      Handler: !Ref Handler
      Role: !Ref LambdaExecutionRoleArn
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key

Outputs:
  LambdaArn:
    Description: The ARN of the Lambda function.
    Value: !GetAtt LambdaFunction.Arn
