AWSTemplateFormatVersion: 2010-09-09
Description: Integrates a Lambda with a given ReST API, creating a resource and a method, without creating the ReST API itself

Parameters:
  RestApiId:
    Type: String
    Description: The ID of the REST API Gateway.
  RootResourceId:
    Type: String
    Description: The ID of the root resource on the REST API Gateway.
  LambdaFunctionArn:
    Type: String
    Description: The ARN of the Lambda function to integrate with the REST API.
  LambdaFunctionUri:
    Type: String
    Description: The URI of the Lambda function to integrate with the REST API.
  ResourceName:
    Type: String
    Description: The name of the resource.
  HTTPMethod:
    Type: String
    Description: The HTTP method to use for the integration.
    Default: GET
  ContentHandling:
    Type: String
    Description: The content handling method to use for the integration.
    Default: CONVERT_TO_TEXT
  StageName:
    Type: String
    Description: The name of the stage.
    Default: 'dev'

Resources:
  LambdaResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApiId
      ParentId: !Ref RootResourceId
      PathPart: !Ref ResourceName

  LambdaMethod:
    Type: AWS::ApiGateway::Method
    DependsOn: LambdaResource
    Properties:
      HttpMethod: !Ref HTTPMethod
      AuthorizationType: NONE
      ResourceId: !Ref LambdaResource
      RestApiId: !Ref RestApiId
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS
        Uri: !Ref LambdaFunctionUri
        PassthroughBehavior: WHEN_NO_MATCH
        IntegrationResponses:
          - StatusCode: '200'
        ContentHandling: !Ref ContentHandling
        TimeoutInMillis: 29000
        CacheNamespace: !Ref LambdaResource
        CacheKeyParameters: []

  APIDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: LambdaMethod
    Properties:
      RestApiId: !Ref RestApiId
      Description: !Sub Deployment for ${StageName}
      StageName: !Ref StageName

  APIStage:
    Type: AWS::ApiGateway::Stage
    DependsOn: APIDeployment
    Properties:
      DeploymentId: !Ref APIDeployment
      RestApiId: !Ref RestApiId
      StageName: !Ref StageName
