AWSTemplateFormatVersion: 2010-09-09
Description: Integrates a Lambda with a given ReST API, creating a resource and a method, without creating the ReST API itself

Parameters:
  RestApiId:
    Type: String
    Description: The ID of the REST API Gateway.
  RootResourceId:
    Type: String
    Description: The ID of the root resource on the REST API Gateway.
  LambdaFunctionArn:
    Type: String
    Description: The ARN of the Lambda function to integrate with the REST API.
  LambdaFunctionUri:
    Type: String
    Description: The URI of the Lambda function to integrate with the REST API.
  ResourceName:
    Type: String
    Description: The name of the resource.
  HTTPMethod:
    Type: String
    Description: The HTTP method to use for the integration.
    Default: GET
  ContentHandling:
    Type: String
    Description: The content handling method to use for the integration.
    Default: CONVERT_TO_TEXT
  StageName:
    Type: String
    Description: The name of the stage.
    Default: 'dev'

Resources:
  LambdaResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApiId
      ParentId: !Ref RootResourceId
      PathPart: !Ref ResourceName

  LambdaMethod:
    Type: AWS::ApiGateway::Method
    DependsOn: LambdaResource
    Properties:
      HttpMethod: !Ref HTTPMethod
      AuthorizationType: NONE
      ResourceId: !Ref LambdaResource
      RestApiId: !Ref RestApiId
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Ref LambdaFunctionUri
        PassthroughBehavior: WHEN_NO_MATCH
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunctionArn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApiId}/*/${HTTPMethod}/${ResourceName}

  APIDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: LambdaMethod
    Properties:
      RestApiId: !Ref RestApiId
      Description: !Sub Deployment for ${StageName}
      StageName: !Ref StageName

  MethodOptions:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: OPTIONS
      ResourceId: !GetAtt LambdaResource
      RestApiId: !Ref RestApiId
      Integration:
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST,GET'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ''
        Type: MOCK
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true
          ResponseModels:
            application/json: 'Empty'
