AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Lambda Layer

Parameters:
  LayerName:
    Type: String
    Description: Name of the Lambda Layer

  S3Bucket:
    Type: String
    Description: Name of the S3 bucket containing the layer ZIP file

  S3Key:
    Type: String
    Description: Key to the layer ZIP file in the S3 bucket

Resources:
  MyLambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Ref LayerName
      Description: My custom Lambda Layer
      Content:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key
      CompatibleRuntimes:
        - python3.10
      LicenseInfo: MIT

Outputs:
  MyLambdaLayerArn:
    Description: The ARN of the Lambda Layer
    Value: !GetAtt MyLambdaLayer.Arn
