AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Lambda Layer

Parameters:
  COSQLayerName:
    Type: String
    Description: Name of the Lambda Layer

  S3Bucket:
    Type: String
    Description: Name of the S3 bucket containing the layer ZIP file

  S3Key:
    Type: String
    Description: Key to the layer ZIP file in the S3 bucket

  Runtime:
    Type: String
    Description: The runtime environment for the Lambda function
    Default: 'python3.10'

Resources:
  COSQLambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Ref COSQLayerName
      Description: My custom Lambda Layer
      Content:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key
      CompatibleRuntimes:
        - !Ref Runtime
      LicenseInfo: MIT

Outputs:
  COSQLambdaLayerARN:
    Description: The ARN of the Lambda Layer
    Value: !GetAtt COSQLambdaLayer.Arn
