name: Create Python Layer
on:
  workflow_dispatch:
    inputs:
      artifact_name:
        description: 'Artifact name'
        required: true
        default: 'cosq-python-layer'

jobs:
  build-layer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependiencies
        run: |
          mkdir -p ${{ inputs.artifact_name }}/python/lib/python3.10/site-packages
          pip install -t ${{ inputs.artifact_name }}/python/lib/python3.10/site-packages psycopg2-binary
        shell: bash

      - name: Create Archive
        run: |
          cd ${{ inputs.artifact_name }}
          zip -r ../${{ inputs.artifact_name }}.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_name }}.zip
