name: Create Python Layer
on:
  workflow_dispatch:
    inputs:
      artifact_name:
        description: 'Artifact name'
        required: true
        default: 'cosq-python-layer'
      s3_bucket:
        description: 'S3 Bucket'
        required: true
        default: 'cosq-layers-dev'

jobs:
  build-layer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependiencies
        run: |
          mkdir -p ${{ inputs.artifact_name }}/python/lib/python3.10/site-packages
          pip install -t ${{ inputs.artifact_name }}/python/lib/python3.10/site-packages psycopg2-binary
        shell: bash

      - name: Create Archive
        run: |
          cd ${{ inputs.artifact_name }}
          zip -r ../${{ inputs.artifact_name }}.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_name }}.zip

  deploy-layer:
    needs: build-layer
    uses: cosq-network/common-workflows/.github/workflows/deploy-layer.yml@main
    with:
      archive: ${{ inputs.artifact_name }}.zip
      layer_name: ${{ inputs.artifact_name }}
      S3Key: ${{ inputs.artifact_name }}.zip
      S3Bucket: ${{ inputs.s3_bucket }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_REGION_DEV }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
