name: Create Python Layer
on:
  workflow_dispatch:
    inputs:
      artifact_name:
        description: 'Artifact name'
        required: true
        default: 'psycopg2-binary-layer'

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install psycopg2-binary
        run: |
          mkdir -p python/lib/python3.10/site-packages
          pip install -t python/lib/python3.10/site-packages psycopg2-binary
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.artifact_name }}
          path: python
